root - INFO - 2023-05-04 11:35:41.025098 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-05-04 11:35:41.155812 - OMS Backend mainloop started.
root - CRITICAL - CRITICAL ERROR:2023-05-04 11:35:41.733682 - OMSB_ADSINT_2
['Traceback (most recent call last):', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 379, in _make_request', '    httplib_response = conn.getresponse(buffering=True)', "TypeError: getresponse() got an unexpected keyword argument 'buffering'", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/ADS_Interface.py", line 52, in get_user_data', "    return json.loads(self.get('get/user_data'))", '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/ADS_Interface.py", line 40, in get', '    response = requests.get(self.url + route, headers=headers)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/api.py", line 70, in get', "    return request('get', url, params=params, **kwargs)", '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/api.py", line 56, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 488, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 609, in send', '    r = adapter.send(request, **kwargs)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 413, in send', '    resp = conn.urlopen(', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen', '    httplib_response = self._make_request(conn, method, url,', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request', '    httplib_response = conn.getresponse()', '  File "/Users/vishaljha/anaconda3/lib/python3.8/http/client.py", line 1332, in getresponse', '    response.begin()', '  File "/Users/vishaljha/anaconda3/lib/python3.8/http/client.py", line 303, in begin', '    version, status, reason = self._read_status()', '  File "/Users/vishaljha/anaconda3/lib/python3.8/http/client.py", line 264, in _read_status', '    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")', '  File "/Users/vishaljha/anaconda3/lib/python3.8/socket.py", line 669, in readinto', '    return self._sock.recv_into(b)', 'KeyboardInterrupt']
