root - INFO - 2023-03-13 23:52:33.204668 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-03-13 23:52:33.308281 - OMS Backend mainloop started.
root - INFO - 2023-03-13 23:52:35.250666 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-03-13 23:52:42.221069 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-03-13 23:52:42.662879 - Attempting XTS login.
root - INFO - 2023-03-13 23:52:42.824494 - ODIN login for NB01.
root - INFO - 2023-03-13 23:52:43.357994 - ODIN login succesful for NB01.
root - INFO - 2023-03-13 23:52:43.476095 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-03-13 23:52:49.494298 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-03-13 23:52:49.844214 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-03-13 23:52:55.662200 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-03-13 23:54:21.573010 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-03-13 23:54:21.675373 - OMS Backend mainloop started.
root - INFO - 2023-03-13 23:54:23.599861 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-03-13 23:54:30.594724 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-03-13 23:54:30.947929 - Attempting XTS login.
root - INFO - 2023-03-13 23:54:31.102304 - ODIN login for NB01.
root - INFO - 2023-03-13 23:54:31.663304 - ODIN login succesful for NB01.
root - INFO - 2023-03-13 23:54:31.784699 - OMSB: Zerodha login for WG5235.
root - CRITICAL - CRITICAL ERROR:2023-03-13 23:54:33.033733 - Failed to generate user dictionary.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 76, in main_loop', '    user_dict = UserProfileGenerator().create_user_profiles(user_data=user_data, log_interface=self.log_interface, debug=self.DEBUG)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/UserProfileGenerator.py", line 69, in create_user_profiles', '    t.join()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1053, in join', '    self._wait_for_tstate_lock()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1073, in _wait_for_tstate_lock', '    if lock.acquire(block, timeout):', 'KeyboardInterrupt']
root - CRITICAL - CRITICAL ERROR:2023-03-13 23:54:33.048511 - OMSB: Failed auto login to kite for user:WG5235.
['Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request', '    six.raise_from(e, None)', '  File "<string>", line 3, in raise_from', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request', '    httplib_response = conn.getresponse()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse', '    response.begin()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin', '    version, status, reason = self._read_status()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 289, in _read_status', '    raise RemoteDisconnected("Remote end closed connection without"', 'http.client.RemoteDisconnected: Remote end closed connection without response', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginZerodha.py", line 37, in automate_login', '    browser.get(browser_url)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 437, in get', "    self.execute(Command.GET, {'url': url})", '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 423, in execute', '    response = self.command_executor.execute(driver_command, params)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 333, in execute', '    return self._request(command_info[0], url, body=data)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 355, in _request', '    resp = self._conn.request(method, url, body=body, headers=headers)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/request.py", line 78, in request', '    return self.request_encode_body(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/request.py", line 170, in request_encode_body', '    return self.urlopen(method, url, **extra_kw)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/poolmanager.py", line 376, in urlopen', '    response = conn.urlopen(method, u.request_uri, **kw)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen', '    retries = retries.increment(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment', '    raise six.reraise(type(error), error, _stacktrace)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise', '    raise value.with_traceback(tb)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request', '    six.raise_from(e, None)', '  File "<string>", line 3, in raise_from', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request', '    httplib_response = conn.getresponse()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse', '    response.begin()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin', '    version, status, reason = self._read_status()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 289, in _read_status', '    raise RemoteDisconnected("Remote end closed connection without"', "urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 71, in start', '    self.process = subprocess.Popen(cmd, env=self.env,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__', '    self._execute_child(args, executable, preexec_fn, close_fds,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child', '    raise child_exception_type(errno_num, err_msg, err_filename)', "FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginZerodha.py", line 117, in auto_login_zerodha', '    key = automate_login(browser_url, user_id, password, totp_pin)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginZerodha.py", line 40, in automate_login', '    browser = webdriver.Chrome(options = options)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__', '    super(WebDriver, self).__init__(DesiredCapabilities.CHROME[\'browserName\'], "goog",', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__', '    self.service.start()', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start', '    raise WebDriverException(', "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home", '']
root - CRITICAL - CRITICAL ERROR:2023-03-13 23:54:33.161311 - Failure in order handler.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 82, in main_loop', '    order_handler = OrderHandler(user_profiles=user_dict, spread_list=spread_list, log_interface = self.log_interface, debug=self.DEBUG)', "UnboundLocalError: local variable 'user_dict' referenced before assignment"]
root - INFO - 2023-03-13 23:54:33.213827 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-03-13 23:54:36.360029 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-03-13 23:54:36.462535 - OMS Backend mainloop started.
root - INFO - 2023-03-13 23:54:38.427488 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-03-13 23:54:45.325747 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-03-13 23:54:45.705918 - Attempting XTS login.
root - INFO - 2023-03-13 23:54:45.875719 - ODIN login for NB01.
root - INFO - 2023-03-13 23:54:46.419010 - ODIN login succesful for NB01.
root - INFO - 2023-03-13 23:54:46.533961 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-03-13 23:54:52.795695 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-03-13 23:54:52.918574 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-03-13 23:54:59.694927 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-03-13 23:54:59.903046 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:583.
root - INFO - 2023-03-13 23:54:59.904074 - Placed ODIN options order for:ODIN, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:178.
root - CRITICAL - CRITICAL ERROR:2023-03-13 23:55:00.074115 - Failed to update order placement in DB. User: ODIN. Tradingsymbol:NIFTY2331617200CE. QTY:-50.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OrderPlacement.py", line 318, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price, spread_list=spread_list) # If this fails, infinite order placement -> stop this thread + critical user message', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/DBManager.py", line 447, in update_order_placement', '    update_orderbuffer(username=username,tradingsymbol=tradingsymbol,placed_qty=placed_qty,placed_price=placed_price,cur=cur, spread_list= spread_list, debug=debug)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/DBManager.py", line 382, in update_orderbuffer', '    update_order_reference(username=username, position_list=positions_list, placed_price=new_placement_price,order_completion=order_completion,cur=cur, spread_list=spread_list, rollover = rollover, debug=debug)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/DBManager.py", line 435, in update_order_reference', "    cur.execute('UPDATE order_reference SET position_status = {} WHERE order_id = {} and tradingsymbol = {};'.format(gSF(order_completion),order_id,gSF(tradingsymbol)))", 'sqlite3.OperationalError: near "input": syntax error']
root - INFO - 2023-03-13 23:55:00.412910 - Placed Zerodha Kite options order for:FINVANT_LIVE, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:580.
root - INFO - 2023-03-13 23:55:01.431204 - 1530.0660133361816
root - CRITICAL - CRITICAL ERROR:2023-03-13 23:55:01.482819 - Failed to update order placement in DB. User: FINVANT_LIVE. Tradingsymbol:NIFTY2331617200CE. QTY:-50.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OrderPlacement.py", line 132, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price, spread_list=spread_list, debug=debug) # If this fails, infinite order placement -> stop this thread + critical user message', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/DBManager.py", line 447, in update_order_placement', '    update_orderbuffer(username=username,tradingsymbol=tradingsymbol,placed_qty=placed_qty,placed_price=placed_price,cur=cur, spread_list= spread_list, debug=debug)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/DBManager.py", line 382, in update_orderbuffer', '    update_order_reference(username=username, position_list=positions_list, placed_price=new_placement_price,order_completion=order_completion,cur=cur, spread_list=spread_list, rollover = rollover, debug=debug)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/DBManager.py", line 435, in update_order_reference', "    cur.execute('UPDATE order_reference SET position_status = {} WHERE order_id = {} and tradingsymbol = {};'.format(gSF(order_completion),order_id,gSF(tradingsymbol)))", 'sqlite3.OperationalError: near "input": syntax error']
root - INFO - 2023-03-13 23:55:08.001763 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:459.
root - INFO - 2023-03-13 23:55:08.106500 - 105.24201393127441
root - INFO - 2023-03-13 23:55:15.000589 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:612.
root - INFO - 2023-03-13 23:55:15.105617 - 105.38768768310547
root - INFO - 2023-03-13 23:55:22.001968 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:872.
root - INFO - 2023-03-13 23:55:22.109794 - 108.80875587463379
root - INFO - 2023-03-13 23:55:29.001219 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:276.
root - INFO - 2023-03-13 23:55:29.105092 - 104.26497459411621
root - INFO - 2023-03-13 23:55:36.001498 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:649.
root - INFO - 2023-03-13 23:55:36.122837 - 121.76203727722168
root - INFO - 2023-03-13 23:55:43.001903 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:824.
root - INFO - 2023-03-13 23:55:43.129233 - 127.777099609375
root - INFO - 2023-03-13 23:55:48.874455 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-03-13 23:55:48.999314 - OMS Backend mainloop started.
root - INFO - 2023-03-13 23:55:50.990601 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-03-13 23:55:57.941571 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-03-13 23:55:58.325717 - Attempting XTS login.
root - INFO - 2023-03-13 23:55:58.479186 - ODIN login for NB01.
root - INFO - 2023-03-13 23:55:58.974391 - ODIN login succesful for NB01.
root - INFO - 2023-03-13 23:55:59.083356 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-03-13 23:56:05.843058 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-03-13 23:56:05.955105 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-03-13 23:56:12.203197 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-03-13 23:56:12.309155 - Placed ODIN options order for:ODIN, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:700.
root - INFO - 2023-03-13 23:56:12.309372 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:101.
root - INFO - 2023-03-13 23:56:12.416227 - 108.63184928894043
root - INFO - 2023-03-13 23:56:12.485619 - 178.6971092224121
root - INFO - 2023-03-13 23:56:12.816255 - Placed Zerodha Kite options order for:FINVANT_LIVE, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:676.
root - INFO - 2023-03-13 23:56:12.926521 - 618.645191192627
root - INFO - 2023-03-13 23:56:19.001535 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:171.
root - INFO - 2023-03-13 23:56:19.127550 - 126.35493278503418
root - INFO - 2023-03-13 23:56:26.002074 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:-50, transaction type:SELL, placed price:110.25, id:315.
root - INFO - 2023-03-13 23:56:26.129260 - 128.24106216430664
root - INFO - 2023-03-13 23:56:54.603958 - Placed ODIN options order for:ODIN, instrument:NIFTY2331617200CE, qty:50, transaction type:BUY, placed price:110.25, id:442.
root - INFO - 2023-03-13 23:56:54.604554 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:50, transaction type:BUY, placed price:110.25, id:842.
root - INFO - 2023-03-13 23:56:54.713196 - 109.73310470581055
root - INFO - 2023-03-13 23:56:54.841333 - 237.10894584655762
root - INFO - 2023-03-13 23:56:55.103407 - Placed Zerodha Kite options order for:FINVANT_LIVE, instrument:NIFTY2331617200CE, qty:50, transaction type:BUY, placed price:110.25, id:983.
root - INFO - 2023-03-13 23:56:55.223936 - 621.1562156677246
root - INFO - 2023-03-13 23:57:01.001580 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:50, transaction type:BUY, placed price:110.25, id:95.
root - INFO - 2023-03-13 23:57:01.118741 - 117.74373054504395
root - INFO - 2023-03-13 23:57:08.001117 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:50, transaction type:BUY, placed price:110.25, id:555.
root - INFO - 2023-03-13 23:57:08.108832 - 108.73985290527344
root - INFO - 2023-03-13 23:57:15.002870 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:50, transaction type:BUY, placed price:110.25, id:485.
root - INFO - 2023-03-13 23:57:15.115738 - 114.43805694580078
root - INFO - 2023-03-13 23:57:22.002207 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:50, transaction type:BUY, placed price:110.25, id:787.
root - INFO - 2023-03-13 23:57:22.114322 - 113.44695091247559
root - INFO - 2023-03-13 23:57:29.001209 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:50, transaction type:BUY, placed price:110.25, id:731.
root - INFO - 2023-03-13 23:57:29.126837 - 126.43098831176758
root - INFO - 2023-03-13 23:57:36.002367 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:50, transaction type:BUY, placed price:110.25, id:470.
root - INFO - 2023-03-13 23:57:36.116865 - 115.28301239013672
root - INFO - 2023-03-13 23:57:43.001378 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:50, transaction type:BUY, placed price:110.25, id:918.
root - INFO - 2023-03-13 23:57:43.113951 - 113.59214782714844
root - INFO - 2023-03-13 23:57:50.001807 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:50, transaction type:BUY, placed price:110.25, id:913.
root - INFO - 2023-03-13 23:57:50.130548 - 129.1201114654541
root - INFO - 2023-03-13 23:57:57.000828 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY2331617200CE, qty:50, transaction type:BUY, placed price:110.25, id:113.
root - INFO - 2023-03-13 23:57:57.115056 - 114.56513404846191
